import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UseShoppingCartProvider } from "./contexts/useShoppingCart";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Street Tech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <UseShoppingCartProvider>
          {children}
        </UseShoppingCartProvider>
      </body>
    </html>
  );
}
